create table public.media (
  id bigint generated by default as identity primary key,

  anilist_id integer unique not null,

  type text not null,

  title text not null,
  title_native text,

  description text,

  cover_image text,
  banner_image text,

  genres text[] not null default '{}',

  status text,

  episodes integer,
  chapters integer,

  season text,
  season_year integer,

  average_score numeric(5,2),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint media_type_check
    check (
      type in (
        'ANIME',
        'MANGA'
      )
    )
);

create index media_anilist_id_idx
  on public.media(anilist_id);

create index media_type_idx
  on public.media(type);

create index media_title_idx
  on public.media(title);

create index media_year_idx
  on public.media(season_year);

alter table public.media enable row level security;

create policy "Anyone can read media"
  on public.media
  for select
  using (true);